# Generated by Django 4.1.4 on 2022-12-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fieldName',
            new_name='image',
        ),
    ]
