# Generated by Django 4.1.4 on 2022-12-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0002_rename_fieldname_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emsapp.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emsapp.district'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emsapp.post'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
