# Generated by Django 4.1.4 on 2022-12-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0003_alter_employee_department_alter_employee_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
