# Generated by Django 4.1.4 on 2022-12-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0004_dailytask_delivery_date_alter_meeting_meeting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='dailytask',
            name='delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
