# Generated by Django 4.1.4 on 2022-12-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0005_remove_dailytask_delivery_date_dailytask_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
