# Generated by Django 4.1.4 on 2022-12-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0006_alter_dailytask_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='district',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='post',
        ),
    ]
