# Generated by Django 4.1.4 on 2022-12-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0008_alter_employee_email_alter_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='user',
        ),
    ]
